title: Haiku of Sev'ral / Cloud Native Developers' / Misery at Work
email: null
description: >- 
  ...
baseurl: ""
url: https://chrispyduck.github.io/haiku/
domain: chrispyduck.github.io
plugins: []
exclude: 
- Gemfile
- Gemfile.lock