title: Haiku of Sev'ral / Cloud Native Developers' / Misery at Work
email: null
description: >- 
  ...
baseurl: /haiku
url: https://chrispyduck.github.io/haiku/
domain: chrispyduck.github.io
plugins: 
- jekyll-datapage-generator
exclude: 
- Gemfile
- Gemfile.lock

page_gen:
- data: authors
  template: author
  dir: authors
  name_expr: record['_id']
  title_expr: '"By Author: " + record["_id"]'
- data: topics
  template: topic
  dir: topics
  name_expr: record['_id']
  title_expr: '"By Topic: " + record["name"]'