title: Haiku of Sev'ral / Cloud Native Developers' / Misery at Work
email: null
description: >- 
  ...
baseurl: ""
url: https://chrispyduck.github.io 
domain: chrispyduck.github.io
#google_analytics: G-QDEXB4N5LL
#theme: null
plugins: []
exclude: 
- Gemfile
- Gemfile.lock

#sidebar_background_image: 