name: "build & publish"
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
      env:
        GCP_API_KEY: ${{secrets.GCP_API_KEY}}
        GH_TOKEN: ${{secrets.GH_TOKEN}}