name: "build & publish"
on:
#  schedule:
#    - cron: "0 * * * *"
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - name: build
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        ssh: |
            default=${{ env.SSH_AUTH_SOCK }}
        build-args: |
          GCP_API_KEY=${{secrets.GCP_API_KEY}}
